- name: Update apt repos and install packages
  hosts: hypervisor
  tasks: 
    - name: Remove Proxmox VE Enterprise repo
      ansible.builtin.apt_repository:
        repo: "deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise"
        state: absent
    - name: Add Proxmox VE No-Subscription Repository to apt repository sources.list
      ansible.builtin.apt_repository:
        repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
        state: present
    - name: Install basic packages
      ansible.builtin.apt:
        name:
          - parted
          - htop
          - atop
          - iotop
          - tcpdump
          - sysstat
          - strace
          - linux-perf
          - screen
          - tmux
          - rsync
          - whois
        state: present

- name: Set up reverse proxy for Proxmox
  hosts: hypervisor
  become: yes
  tags:
    - reverseproxy
  roles:
    - role: "ansible-role-nginx"
  tasks: 
    - name: Update nginx systemd unit
      ansible.builtin.copy:
        src: nginx.service
        dest: /etc/systemd/system/nginx.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - "Restart nginx"
  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

