# From https://pve.proxmox.com/wiki/Web_Interface_Via_Nginx_Proxy
nginx_vhosts:
  - listen: "80"
    server_name: "hypervisor01.libjpel.so"
    extra_parameters: |
      rewrite ^(.*) https://$host$1 permanent;
    filename: "01-hypervisor01-libjpel-so-http.conf"
  - listen: "443 ssl"
    server_name: "hypervisor01.libjpel.so"
    extra_parameters: |
      ssl on;
      ssl_certificate /etc/pve/local/pve-ssl.pem;
      ssl_certificate_key /etc/pve/local/pve-ssl.key;
      proxy_redirect off;
      location / {
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade"; 
          proxy_pass https://localhost:8006;
          proxy_buffering off;
          client_max_body_size 0;
          proxy_connect_timeout  3600s;
          proxy_read_timeout  3600s;
          proxy_send_timeout  3600s;
          send_timeout  3600s;
      }
    filename: "01-hypervisor01-libjpel-so-https.conf"
